# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'CastBridge' do
  use_frameworks!

  # Google Cast SDK per streaming su Chromecast
  pod 'google-cast-sdk', '~> 4.8'

  target 'CastBridgeTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
